### ISSUE TITLE
It became necessary to add 3rd network of VTC p2pool 

### ISSUE THREAD

**Issue by ilsawa** [vertcoin/p2pool-vtc#10]
Miners with powers of about 300 MH/s can no longer normally get shares.
There are already many miners with 200-300 MH/s in the second network.
Therefore I think that there is a need to create a third network for miners with hashrate of up to 100 MH/s.

**Comment by Steffuno** [comment]
I agree. Now I have 80-90mhs.  I was had +3shares 5 hours ago. And now I have - 0. And this second time situation for 3 days. I meen this is wrong.

**Comment by metalicjames** [comment]
Released
