### ISSUE TITLE
Best value for pseudo shares?

### ISSUE THREAD

**Issue by p1r473** [vertcoin/p2pool-vtc#20]
Hi,
Best value for pseudo shares?
The example on main page was 4. Is this optimal?

**Comment by stevecastaneda** [comment]
On the latest release of p2pool-vtc, where setting manual difficulty and psuedoshares is enabled, the calculation is Hashrate in KH * 0.00000116.

So the result will be, if hashing at 50MH:

MYADDRESS+0.058

These options are disabled on any node running the latest pre-release of p2pool-vtc.

**Comment by p1r473** [comment]
I mean, on the server side, for --miner-share-rate

**Comment by stevecastaneda** [comment]
Ah, sorry.  I used 10.  30 was too much, more than a couple of miners and latency went above 5%.  4 seems to take a bit longer than I'm comfortable with to show accurate hashrate, and 10 was a good compromise.

**Comment by p1r473** [comment]
Thanks!
